washroom_cleaner:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  dustbin_controller:
    type: effort_controllers/JointPositionController
    joint: dustbin_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
